### ISSUE TITLE
fake injection

### ISSUE THREAD

**Issue by jacopotediosi** [GiacomoDevIT/GjacBot-SQL#1]
`$conn->query("insert into $tabella (chat_id, status, username) values ($chatID, '', \"".$username."\")");`

$username is a user-controlled input, so it should be sanitized before using it in queries.

**Comment by GiacomoDevIT** [comment]
before using*

**Comment by jacopotediosi** [comment]
Another issue closed without fixing the vulnerability...

**Comment by SparpvpBoii** [comment]
sos

**Comment by GiacomoDevIT** [comment]
Injection that you wrote doesn't exist, and it can't be applied, so I will not change anything since your theory is not true.

**Comment by jacopotediosi** [comment]
If you closed this because of https://github.com/GiacomoDevIT/GjacBot-SQL/commit/f0aa0570c738a093f1cfa4c1607455159afce459#diff-3f6815f020b04008d2cc3c8e94453cadR63, then the SQL Injection is still there. Please learn to correctly use prepared statements and use bind_param instead of directly concatenating variables into queries.
