### ISSUE TITLE
fake injection

### ISSUE THREAD

**Issue by reloonfire** [GiacomoDevIT/GjacBot-SQL#2]
`$conn->query("insert into $tabella (chat_id, status, username) values ($chatID, '', \"".$username."\")");`
$username è una variabile gestita dall'utente, andrebbero fatti dei controlli prima di utilizzarla nelle query 👍

**Comment by GiacomoDevIT** [comment]
vai dal medico allora

**Comment by reloonfire** [comment]
Allora ti suggerisco di modificare anche la descrizione del tuo profilo github. Togli security che non ti compete per nulla :D

**Comment by GiacomoDevIT** [comment]
L'Injection non esiste, non può essere applicata e non modificherò nulla dato che non è una teoria fondata la tua.
